name: Hello World!

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: |
          echo  "Hello World!"

jobs: 
  date_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Now it is
        run: |
          date
jobs: 
  directory_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Directory_Content
        run: |
          ls -l